# TODO: Run $ docker buildx build -f ./Dockerfile_jenkins_master -t custom_jenkins_master:2.520 .
# (important!) Use the working image version from official doc
FROM jenkins/jenkins:2.520-jdk21

USER root

RUN apt-get update && apt-get install -y \
        lsb-release \
        ca-certificates \
        curl && \
    install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc && \
    chmod a+r /etc/apt/keyrings/docker.asc && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
    https://download.docker.com/linux/debian $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" \
    | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    # Install Docker CLI & additional tools
    apt-get update && apt-get install -y \
        docker-ce-cli \
        python3-pip \
        git curl wget telnet iputils-ping && \
    # Install kubectl
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER jenkins

# (Method 1) Keep plugins in a file for repeatability
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli --verbose --plugin-file /usr/share/jenkins/ref/plugins.txt

# (Method 2) Direct plugin install
# RUN jenkins-plugin-cli --verbose --plugins "blueocean docker-workflow json-path-api"
