apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-sa
  imagePullSecrets: # Add this to increase docker pull rate limit
    - name: dockerhub-secret
  containers:
    # (Optional) Pin JNLP image version
    - name: jnlp
      image: jenkins/inbound-agent:3327.v868139a_d00e0-3-jdk21
      imagePullPolicy: IfNotPresent # Use cached image if available
      tty: true
    - name: gradle
      image: gradle:8.14.3-jdk21
      imagePullPolicy: IfNotPresent # Use cached image if available
      command:
        - cat
      tty: true
      env:
        # Complete Gradle configuration (all-in-one)
        - name: GRADLE_OPTS
          value: >-
            -Dorg.gradle.daemon=false
            -Dorg.gradle.parallel=false
            -Dorg.gradle.caching=true
            -Dorg.gradle.console=plain
            -Dorg.gradle.logging.level=lifecycle
            -Dhttp.proxyHost=${env.PROXY_IP}
            -Dhttp.proxyPort=${env.PROXY_PORT}
            -Dhttps.proxyHost=${env.PROXY_IP}
            -Dhttps.proxyPort=${env.PROXY_PORT}
            -Xmx512m
            -XX:MaxMetaspaceSize=256m
      resources:
        requests:
          memory: "512Mi" # Min. requirements otherwise OOM
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"
