apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-sa
  imagePullSecrets: # Add this to increase docker pull rate limit
    - name: dockerhub-secret
    # Or Use below to pull from intenal registry
    # - name: docker-company-secret
  containers:
    # (Optional) Pin JNLP image version
    - name: jnlp
      image: jenkins/inbound-agent:3327.v868139a_d00e0-3-jdk21
      imagePullPolicy: IfNotPresent # Use cached image if available
      tty: true
    - name: node
      image: node:24-alpine3.21
      imagePullPolicy: IfNotPresent # Use cached image if available
      command:
        - cat
      tty: true
      # env:
      # - name: HTTP_PROXY
      #   value: "${env.HTTP_PROXY}"  # Already injected from Jenkins Global Env Vars
      # - name: HTTPS_PROXY
      #   value: "${env.HTTPS_PROXY}"
      # - name: NO_PROXY
      #   value: "${env.NO_PROXY}"
      resources:
        requests:
          memory: "512Mi" # Min. requirements otherwise OOM
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "500m"
