# TODO: Run $ docker buildx build --no-cache --progress=plain -f ./Dockerfile_jenkins_agent_python39_bullseye -t agent:python39-bullseye .
# TODO: Upload image to Docker Registry for Jenkins Master to pull
# TODO: Pull & Run locally for testing or install more pkg: $ docker run -itd --name agent-python agent:python3-bookworm
FROM jenkins/agent:bullseye-jdk17

# Nicer logs in Jenkins steps
ENV PYTHONUNBUFFERED=1

USER root

# Bookworm pkg installation CMD
# Install Python tooling (no recommends) and clean up apt cache
# - python3-venv & python3-pip: usual requirements for builds.
# - `--no-install-recommends` + clean cache: keeps the image smaller.
# - `ln -sf /usr/bin/python /usr/bin/python3`: avoids scripts expecting python.
# - If you need extra libs (e.g., gcc, libssl-dev) for wheels, add them in the same RUN.
# - gcc: For building Python pkg
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc python3-setuptools python3-wheel python3-dev build-essential \
        python3 python3-venv python3-pip && \
    ln -sf /usr/bin/python3 /usr/bin/python && \
    echo '-------- Python Version (v3.9.2) --------' && \
    python --version && pip --version && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER jenkins
